
INSERT INTO ingredient (id_tapa, nom) VALUES
(1, 'Patates'),
(1, 'Salsa brava'),
(1, 'Allioli'),
(1, 'Ceba'),
(2, 'Patates'),
(2, 'Botifarra negra'),
(2, 'Beixamel'),
(2, 'Pa ratllat'),
(3, 'Patates'),
(3, 'Carn picada'),
(3, 'Beixamel'),
(3, 'Pa ratllat'),
(4, 'Patates'),
(4, 'Salsa brava'),
(4, 'Allioli'),
(5, 'Patates'),
(5, 'Salsa brava especial'),
(5, 'Allioli'),
(6, 'Calamares'),
(6, 'Pa de cristal'),
(6, 'Allioli'),
(7, 'Patates'),
(7, 'Carn picada'),
(7, 'Salsa picant secreta'),
(8, 'Perol'),
(8, 'Llet'),
(8, 'Farina'),
(8, 'Pernil ibèric'),
(9, 'Patates'),
(9, 'Reducció de vermut'),
(9, 'Allioli'),
(10, 'Patates'),
(10, 'Ous'),
(10, 'Ceba'),
(11, 'Patates'),
(11, 'Pimentón ahumado'),
(11, 'Allioli'),
(12, 'Patates'),
(12, 'Salsa brava tradicional'),
(12, 'Allioli'),
(13, 'Patates'),
(13, 'Carn picada selecta'),
(13, 'Beixamel'),
(14, 'Polp'),
(14, 'Patata'),
(14, 'Pimentón'),
(15, 'Patates'),
(15, 'Allioli'),
(15, 'Oli picant'),
(16, 'Patates'),
(16, 'Xoriço'),
(16, 'Salsa brava'),
(17, 'Patates'),
(17, 'Carn de vedella'),
(17, 'Beixamel'),
(18, 'Patates'),
(18, 'Salsa brava picant'),
(19, 'Pa'),
(19, 'Tomàquet'),
(19, 'Oli d\'oliva'),
(20, 'Patates'),
(20, 'All negre'),
(20, 'Salsa brava'),
(21, 'Ous'),
(21, 'Patates'),
(21, 'Pernil ibèric'),
(22, 'Patates'),
(22, 'Barreja de carns'),
(22, 'Beixamel'),
(23, 'Pa'),
(23, 'Llom'),
(23, 'Pebrots'),
(24, 'Patates'),
(24, 'Salsa brava espessa'),
(25, 'Patates'),
(25, 'Carn de porc'),
(25, 'Beixamel'),
(26, 'Patates'),
(26, 'Salsa brava'),
(26, 'Allioli'),
(27, 'Patates'),
(27, 'Reducció de vermut'),
(27, 'Allioli'),
(28, 'Patates'),
(28, 'Carn de bou'),
(28, 'Beixamel'),
(29, 'Patates'),
(29, 'Butifarra de ceba'),
(30, 'Patates'),
(30, 'Sofregit'),
(30, 'Oli picant'),
(31, 'Patates'),
(31, 'Carn picada'),
(31, 'Beixamel'),
(32, 'Pebrots del Padrón'),
(32, 'Sal gruixuda'),
(32, 'Oli d\'oliva'),
(33, 'Anxoves'),
(33, 'All'),
(33, 'Julivert'),
(33, 'Vinagre'),
(34, 'Patates'),
(34, 'Salsa brava'),
(34, 'Oli de llimona'),
(35, 'Gambes'),
(35, 'All'),
(35, 'Guindilla'),
(36, 'Patates'),
(36, 'Carn de xai'),
(36, 'Beixamel'),
(37, 'Patates'),
(37, 'Salsa brava'),
(37, 'Salsa allioli'),
(38, 'Patates'),
(38, 'Carn de vedella'),
(38, 'Beixamel');
